name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repo
      with:
        submodules: true

    - id: log
      name: Store Commit Message
      run: echo "POST_COMMIT_MESSAGE=$(git log --no-merges -1 --pretty=%B)" >> $GITHUB_ENV

    - name: Parse Commit Message for Title/Url/Message
      env:
         COMMIT: ${{ env.POST_COMMIT_MESSAGE }}
      run: ./scripts/parse-commit.sh

    - id: output
      name: Write Parse Commit Message
      run: echo "${{ env.COMMIT_TITLE }} ${{ env.COMMIT_URL }} ${{ env.COMMIT_CONTENT }}"

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.4.13
      with:
        hugo-version: "latest"

    - name: Build App
      run: hugo --minify

    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v0.0.1-preview
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_POND_0404A9D1E }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: "upload"
        ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: "public" # App source code path
        api_location: "" # Api source code path - optional
        skip_app_build: true
        ###### End of Repository/Build Configurations ######


    - uses: ethomson/send-tweet-action@v1
      name: Send Tweet
      if: env.COMMIT_URL != ''
      with:
        status: "NEW BLOG POST: ${{ env.COMMIT_TITLE }} \n ${{ env.COMMIT_URL }} \n ${{ env.COMMIT_CONTENT }}"
        consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

    - uses: BjornLuG/release-for-reddit-action@v1
      name: Post to Reddit
      if: env.COMMIT_URL != ''
      with:
        username: ${{ secrets.REDDIT_USERNAME }}
        password: ${{ secrets.REDDIT_PASSWORD }}
        app-id: ${{ secrets.REDDIT_APP_ID }}
        app-secret: ${{ secrets.REDDIT_APP_SECRET }}
        subreddit: dotnet
        title: "${{ env.COMMIT_TITLE }}"
        url: "${{ env.COMMIT_URL }}"

    - name: Post to LinkedIn
      uses: fjogeleit/http-request-action@v1.2.0
      if: env.COMMIT_URL != ''
      with:
        url: ${{ secrets.LOGIC_APP_URL }}
        method: "POST"
        contentType: "application/json"
        data: "{ \"url\": \"${{ env.COMMIT_URL }}\" }"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_POND_0404A9D1E }}
          action: "close"
