name: Build and Publish Blog to Azure Blob Storage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - id: log
        run: echo "::set-env name=POST_COMMIT_MESSAGE::$(git log --no-merges -1 --pretty=%B)"
      - id: parse
        run: "IFS='|' read -ra ::set-env name=COMMIT_ARRAY:: <<< ${{ env.POST_COMMIT_MESSAGE }}"
      - uses: chabad360/hugo-actions@master
        with:
          buildPath: 'public'
          hugoVersion: ''
          args: ''
      - uses: bacongobbler/azure-blob-storage-upload@v1.0.0
        with:
          source_dir: public
          container_name: $web
          connection_string: ${{ secrets.ConnString }}
          extra_args: ''
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "NEW POST: ${{ env.POST_COMMIT_MESSAGE }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      - uses: BjornLuG/release-for-reddit-action@v1
        with:
          username: ${{ secrets.REDDIT_USERNAME }}
          password: ${{ secrets.REDDIT_PASSWORD }}
          app-id: ${{ secrets.REDDIT_APP_ID }}
          app-secret: ${{ secrets.REDDIT_APP_SECRET }}
          subreddit: Azure # Submit to /r/test
          url: "${{ env.COMMIT_ARRAY[1] }}"

