name: Build and Publish Blog to Azure Blob Storage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - id: log
        run: echo "::set-env name=POST_COMMIT_MESSAGE::$(git log --no-merges -1 --pretty=%B)"
      - name: Bash Command Lines for GitHub Actions
        uses: jdickey/bash@v.1.1.1
         args = ["IFS='|' read -ra my_array <<< ${{ env.POST_COMMIT_MESSAGE }}"]
