name: Build and Publish Blog to Azure Blob Storage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - id: log
        run: echo "::set-env name=POST_COMMIT_MESSAGE::$(git log --no-merges -1 --pretty=%B)"
      
      - name: parse commit
        env:
           COMMIT: ${{ env.POST_COMMIT_MESSAGE }}
        run: ./scripts/parse-commit.sh        
      - id: output
        run: echo "${{ env.COMMIT_TITLE }} ${{ env.COMMIT_URL }} ${{ env.COMMIT_CONTENT }}"
      
      - uses: actions/checkout@master
      
      - uses: chabad360/hugo-actions@master
        with:
          buildPath: 'public'
          hugoVersion: ''
          args: ''
          
      - uses: bacongobbler/azure-blob-storage-upload@v1.0.0
        with:
          source_dir: public
          container_name: $web
          connection_string: ${{ secrets.ConnString }}
          extra_args: ''
          
      - uses: ethomson/send-tweet-action@v1
        if: env.COMMIT_URL != ''      
        with:
          status: "NEW BLOG POST: ${{ env.COMMIT_TITLE }} \n ${{ env.COMMIT_URL }} \n ${{ env.COMMIT_CONTENT }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          
      - uses: BjornLuG/release-for-reddit-action@v1
        if: env.COMMIT_URL != ''    
        with:
          username: ${{ secrets.REDDIT_USERNAME }}
          password: ${{ secrets.REDDIT_PASSWORD }}
          app-id: ${{ secrets.REDDIT_APP_ID }}
          app-secret: ${{ secrets.REDDIT_APP_SECRET }}
          subreddit: Azure
          title: "${{ env.COMMIT_TITLE }}" 
          url: "${{ env.COMMIT_URL }}"
          
      - name: Post to LinkedIn
        uses: fjogeleit/http-request-action@v1.2.0
        if: env.COMMIT_URL != ''    
        with:
          url: ${{ secrets.LOGIC_APP_URL }}
          method: "POST" 
          contentType: "application/json"
          data: "{ \"url\": \"${{ env.COMMIT_URL }}\" }"   
