name: Build and Publish Blog to Azure Blob Storage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - id: log
        run: echo "::set-env name=POST_COMMIT_MESSAGE::$(git log --no-merges -1 --pretty=%B)"
      - id: parse
        run: echo "IFS='|' read -ra my_array <<< $COMMIT" && echo "::set-env name=COMMIT_ARRAY:'foo|bar'"
        env:
          COMMIT: ${{ env.POST_COMMIT_MESSAGE }}
      - id: output
        run: echo "${{ env.COMMIT_ARRAY }}"
