name: Build and Publish Blog to Azure Blob Storage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - id: log
        run: echo "::set-env name=POST_COMMIT_MESSAGE::$(git log --no-merges -1 --pretty=%B)"
      - name: parse commit
        env:
           COMMIT: ${{ env.POST_COMMIT_MESSAGE }}
        run: ./scripts/parse-commit.sh        
      - id: output
        run: echo "${{ env.COMMIT_TITLE }} ${{ env.COMMIT_URL }} ${{ env.COMMIT_CONTENT }}"
      - name: Post Blog to LinkedIn
        uses: fjogeleit/http-request-action@v1.1.0
        with:
          url: ${{ secrets.LOGIC_APP_URL }}
          method: "POST" 
          contentType: "application/json"
          data: "${{ env.COMMIT_URL }}"   
