name: Build and Publish Blog to Azure Blob Storage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - id: log
        run: echo "::set-env name=POST_COMMIT_MESSAGE::$(git log --no-merges -1 --pretty=%B)"
      - name: does a thing
        env:
           COMMIT: ${{ env.POST_COMMIT_MESSAGE }}
        run: ./scripts/parse-commit.sh
        
      - id: output
        run: echo "${{ env.COMMIT_ARRAY[1] }}"
